### ISSUE TITLE
Presets tab toggling 

### ISSUE THREAD

**Issue by Blackace65** [tuntorius/mightier_amp#84] opened 2023-10-27 13:17 UTC
I have recently noticed I cannot toggle back to the preset tab after clicking on the editor tab. All QR codes download perfectly into presets but once I view in the editor tab I need to exit the app to gain access to my saved presets again. All other tabs work fine.

**Comment by tuntorius** [comment] 2023-10-31 20:13
I'm closing this as it's a duplicate of #80

**Closed by tuntorius** 2023-10-31 20:13 UTC
