### ISSUE TITLE
Loading presets NUX MP2

### ISSUE THREAD

**Issue by JK5150** [tuntorius/mightier_amp#6] opened 2021-05-24 12:36 UTC
Hello! Sorry, may be I'm stupid, but...how can I load preset to channel? Cannot catch it... Save - ok, but load? 🤔

**Comment by JK5150** [comment] 2021-05-24 13:03
I just want to do this - make 1 and 3 channel the same and 2 and 4 - the same too. In that case I can turn between solo and rhythm modes by just one button click 🙂

**Comment by tuntorius** [comment] 2021-05-24 22:20
If you are talking about the in-app presets, you don't load them into a channel, because they already have the channel associated and they are always loaded in that channel. You load them by going to the second (Presets) tab and tapping on one of them.

About your second post: you can achieve the thing you want by following these steps:
1. Create the 2 presets like this: switch to green channel in the editor, create preset 1 and save it. Then switch to Yellow channel, create preset 2 and save it.
2. Go to Presets tab and create a duplicate of each of those 2 presets by using the vertical dots menu on each one and then tapping on Duplicate. You can rename the new ones to something meaningful if you want. Then select "Change Channel" from the vertical dots menu on the duplicate of the green one. Choose the Drive (Red) channel in the popup that opens. Do the same for the yellow duplicate but set it to acoustic channel.
3. Load the first preset and go to the first (Editor) tab. Tap on the "download" button (The one on the top right with the down arrow). This will download the preset to the green channel of the device. Repeat the same with the 3 other presets.

I know this is far from optimal but for now it's the only way. I have some ideas how to optimize this.
Also bear in mind that you'll get different sound when using the acoustic channel even if you set it up exactly like one of the others. The effects chain is arranged differently there. The IR is before the amp, just like the original app displays it. I found that out only recently but unfortunately there's no way to change it.

**Comment by JK5150** [comment] 2021-06-05 20:27
Thanks you very much!
But maybe there is some opportunity to just lock osme channels? Finally just turning between 2 channels
--
Отправлено из Mail.ru для Android вторник, 25 мая 2021г., 02:20 +04:00 от tuntorius  ***@***.*** :

**Comment by tuntorius** [comment] 2021-06-06 21:48
Unfortunately not. There is no such command over bluetooth. I can think of one workaround though - if the app detects that the amp is switched to a channel you want disabled, it will make it directly jump to the next enabled one. It won't work standalone and will probably pop but still is worth trying.

**Comment by JK5150** [comment] 2021-06-07 09:31
You mean - standalone - only while connected with app?
And another question - is there opportunity to off IR? In case of playing without IR I can plug in "return" insert in real amp and it would be incredible, I think
P.s. how could I send you a donate without paypal? 🙂
Unfortunately I haven't paypal
But your work is great, and I want to support it a bit 🤏😊
--
Отправлено из Mail.ru для Android понедельник, 07 июня 2021г., 01:48 +04:00 от tuntorius  ***@***.*** :

**Comment by tuntorius** [comment] 2021-06-07 12:28
By standalone I mean using the amp as is, without being connected to your phone. This workaround would be possible only when the app is connected so it can mess around with channel switching.

The IR and amp sections can't be turned off. Many people asked me about that but there's no such command. Only NUX can do this by device firmware update. Maybe if enough people request it from them, they might consider adding a command to turn it off. I'm pretty sure it's very simple to implement.

About donation - paypal allows sending donations from debit/credit cards without registering an account, if you are ok with that - just click the donate button and it let you choose which option you prefer.

**Closed** 2022-02-15 23:19 UTC
